- name: Cau hinh tren thiet bi R2
  hosts: Router
  gather_facts: no

  tasks:
    - name: Dat IP cho cac cong
      with_items: "{{ interface }}"
      ios_l3_interfaces:
        config:
        - name: "{{ item.name }}"
          ipv4:
          - address: "{{ item.ip }}" 
    - name: No shut cac cong
      with_items: "{{ interface }}"
      ios_interfaces:
        config: 
        - name: "{{ item.name }}"
          enabled: true
    - name: Cau hinh static route tren R2
      with_items: "{{ route }}"
      ios_static_route:
        prefix: "{{ prefix }}"
        mask: "{{ mask }}"
        next_hop: "{{ next_hop }}"
    - name: show
      ios_command:
        commands:
          - show ip inter br
          - show ip route
      register: show
    - debug: var=show.stdout_lines
      
